name: dls
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/msxenon/dls

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
